apiVersion: v1
kind: Deployment
metadata:
  name: chat-bot
spec:
  containers:
    name: chat-bot
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
    image: langchain_demo:latest